language: node_js

node_js:
  - lts/*
  - node

# install: npm ci
#   - npm ci
#   - npm install -g codecov

jobs:
  include:
    # defaults to stage: test...
    - script: npm run lint

    - script: npm run test

    - script: npm run coverage
      after_success: npm run codecov

    - stage: release
      node_js: lts/*
      if: branch = master
      # overwrite default script?
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
