#!/bin/sh -xe

YEAR="2017"
PROG="node ./index.js"
ARGS="--after ${YEAR}-01-01 --before ${YEAR}-03-31"
OUTPATH="_output/${YEAR}"

${PROG} ${ARGS} --sku edbooth${YEAR}  --out ${OUTPATH}-ed-booths.csv
${PROG} ${ARGS} --sku grooming${YEAR} --out ${OUTPATH}-grooming.csv
${PROG} ${ARGS} --sku ${YEAR}parking  --out ${OUTPATH}-parking.csv
${PROG} ${ARGS} --sku tour${YEAR}     --out ${OUTPATH}-tour.csv
