#!/bin/sh -e

set COMMON = '--after 2017-01-01'

npm start -- ${COMMON} --sku edbooth2017 --out _output/2017-ed-booths.csv
npm start -- ${COMMON} --sku grooming2017 --out _output/2017-grooming.csv
npm start -- ${COMMON} --sku 2017parking --out _output/2017-parking.csv
npm start -- ${COMMON} --sku tour2017 --out _output/2017-tour.csv
