name: build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 20
          #- 22

    # okay... so it's super helpful to not need to re-acquire/re-build, which
    # means putting *everything* into one job.  We just need to be judicious
    # with 'if' to skip some steps based on matrix stuff...
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - run: npm run build --if-present

      - run: npm run lint
      - run: npm run test:dist

      - run: npm run test:dist:coverage

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: build
    if: ${{ needs.build.result == 'success' && github.event_name == 'push' }}

    runs-on: ubuntu-latest

    steps:
      # sadly, we have to re-do the build... but we can skip lint/test
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npm run build --if-present

      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  status:
    needs: [build, release]
    if: ${{ contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    steps:
      - uses: act10ns/slack@v2
        with:
          status: failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
